"""tab position

Revision ID: 1f404697c710
Revises: 41d903e4a608
Create Date: 2025-10-09 14:48:10.638363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f404697c710'
down_revision: Union[str, None] = '41d903e4a608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('_project_user_uc', 'project_user_association', ['project_id', 'user_id'])
    op.drop_constraint('saved_tab_position_key', 'saved_tab', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('saved_tab_position_key', 'saved_tab', ['position'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('_project_user_uc', 'project_user_association', type_='unique')
    # ### end Alembic commands ###
