"""deactivated

Revision ID: 3bf789f6bc8d
Revises: f9127c514fac
Create Date: 2025-12-13 09:43:22.282768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf789f6bc8d'
down_revision: Union[str, None] = 'f9127c514fac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('_project_user_uc', 'project_user_association', ['project_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_project_user_uc', 'project_user_association', type_='unique')
    # ### end Alembic commands ###
