"""group user

Revision ID: 73f1d163f03e
Revises: b5c0fcc52069
Create Date: 2025-08-30 17:17:08.582273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73f1d163f03e'
down_revision: Union[str, None] = 'b5c0fcc52069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'group', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_project_user_uc', 'project_user_association', type_='unique')
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_column('group', 'user_id')
    # ### end Alembic commands ###
