"""change activation code

Revision ID: 9600f466ca58
Revises: 3bf789f6bc8d
Create Date: 2025-12-16 12:45:08.663150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9600f466ca58'
down_revision: Union[str, None] = '3bf789f6bc8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activation_code', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=True))
    op.drop_column('activation_code', 'used_at')
    # op.create_unique_constraint('_project_user_uc', 'project_user_association', ['project_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_project_user_uc', 'project_user_association', type_='unique')
    op.add_column('activation_code', sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('activation_code', 'updated_at')
    # ### end Alembic commands ###
