"""update model image2

Revision ID: aba94f1eb5e7
Revises: d455320fc568
Create Date: 2025-12-05 13:39:37.056214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aba94f1eb5e7'
down_revision: Union[str, None] = 'd455320fc568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('compression_ratio', sa.Float(), nullable=True))
    # op.create_unique_constraint('_project_user_uc', 'project_user_association', ['project_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_project_user_uc', 'project_user_association', type_='unique')
    op.drop_column('image', 'compression_ratio')
    # ### end Alembic commands ###
