"""update model image

Revision ID: d455320fc568
Revises: 2b898c760182
Create Date: 2025-12-05 13:16:24.327602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd455320fc568'
down_revision: Union[str, None] = '2b898c760182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('image', sa.Column('original_size', sa.Integer(), nullable=True))
    # op.create_unique_constraint('_project_user_uc', 'project_user_association', ['project_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_project_user_uc', 'project_user_association', type_='unique')
    op.drop_column('image', 'original_size')
    op.drop_column('image', 'file_size')
    # ### end Alembic commands ###
