"""user restore password

Revision ID: f82042a8b6ca
Revises: 2c90a80c8325
Create Date: 2026-01-03 18:52:21.835695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f82042a8b6ca'
down_revision: Union[str, None] = '2c90a80c8325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('_project_user_uc', 'project_user_association', ['project_id', 'user_id'])
    op.add_column('user', sa.Column('requires_password_reset', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'requires_password_reset')
    op.drop_constraint('_project_user_uc', 'project_user_association', type_='unique')
    # ### end Alembic commands ###
