"""modify roadmap

Revision ID: b5c0fcc52069
Revises: 340fa2c3ad00
Create Date: 2025-08-16 16:02:23.882212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5c0fcc52069'
down_revision: Union[str, None] = '340fa2c3ad00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'chapter', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # op.create_unique_constraint('_project_user_uc', 'project_user_association', ['project_id', 'user_id'])
    op.add_column('stage', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'stage', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stage', type_='foreignkey')
    op.drop_column('stage', 'user_id')
    # op.drop_constraint('_project_user_uc', 'project_user_association', type_='unique')
    op.drop_constraint(None, 'chapter', type_='foreignkey')
    op.drop_column('chapter', 'user_id')
    # ### end Alembic commands ###
